name = "Checkpoint"
uuid = "70d4247f-a84f-4f24-865d-d192c7ff0c55"
authors = ["Scottie Alexander <palexander@lanl.gov>"]
version = "0.1.0"

[deps]
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
UrbanPop = "f3f28a4b-fe4e-413d-beed-473d3cb4e60c"
Workerflow = "35cc5ddd-7890-4ab3-b49b-d7028e71734a"
