name = "PlotHelpers"
uuid = "c81ea056-371b-453c-a44a-9bf38fb76232"
authors = ["Scottie Alexander <palexander@lanl.gov>"]
version = "0.1.0"

[deps]
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"

[compat]
ColorTypes = "0.12.1"
PyCall = "1.96.4"
PyPlot = "2.11.6"
